export const Events = {
    SubmitOrder: "SubmitOrder",
    ChangeViewers: "ChangeViewers",
    ChangeViews: "ChangeViews",
    ChangeSmoothGain: "ChangeSmoothGain",
    ChangeLaunchParams: "ChangeLaunchParams",
    ChangeTariff: "ChangeTariff",
    OrderInitiated: "OrderInitiated",
    Calculate: "Calculate",
    ChangeUrl: "ChangeUrl",
    WatchTask: "WatchTask",
    Run: "Run",
    Stop: "Stop",
    Cancel: "Cancel",
    IncreaseOff: "IncreaseOff",
    ChangeOnlineValue: "change_online_value",
    ChangeIncreaseValue: "change_increase_value",
    IncreaseOn: "increase_on",
    AddViews: "add_views",
    ChangeLaunchMode: "change_launch_mode",
    ChangeDelayTime: "change_delay_time",
}
